---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: percona-backup-notification
rules:
- apiGroups: ["pxc.percona.com"]
  resources: ["perconaxtradbclusterbackups"]
  verbs: ["get", "list", "watch"]
