apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret_name | quote }}
type: Opaque
stringData:
  email_smtp_host: {{ .Values.email.smtp.host | quote }}
  email_smtp_port: {{ .Values.email.smtp.port | quote }}
  email_smtp_username: {{ .Values.email.smtp.username | quote }}
  email_smtp_password: {{ .Values.email.smtp.password | quote }}
